### ISSUE TITLE
demo.htmlのセレクタ

### ISSUE THREAD

**Issue by ghost** [msndo/truncate-text.js#3]
var listElem = document.querySelectorAll('.text-description p');

素朴な疑問なのですが、セレクタは、これが速いですか？

p.content-textなので、
.content-text
だけでも良さそうな気がしたのと

それとも
.text-description .content-text
かな？と思ったのですが、どんなもんでしょうか？

**Comment by msndo** [comment]
.content-textがより妥当、ですね。コメントありがとうございます
反映しました：
https://github.com/msndo/truncate-text.js/commit/6b6f708d0d56410a8ea967218f0ed80a1685daba

@asakon
